wandb_version: 1

_content:
  desc: null
  value:
    model: '{''name'': ''google/bert_uncased_L-2_H-128_A-2'', ''tokenizer'': ''google/bert_uncased_L-2_H-128_A-2''}'
    processing: '{''batch_size'': 64, ''max_length'': 128, ''no-cuda'': False}'
    training: '{''fastmode'': False, ''seed'': 42, ''cuda'': False, ''epochs'': 2,
      ''lr'': 0.01, ''weight_decay'': 0.0005, ''hidden'': 16, ''dropout'': 0.5, ''batch_size'':
      8, ''max_length'': 2708}'
_flags_cache:
  desc: null
  value:
    struct: true
_metadata:
  desc: null
  value: 'ContainerMetadata(ref_type=typing.Any, object_type=None, optional=True,
    key=None, flags={''struct'': True}, flags_root=False, resolver_cache=defaultdict(<class
    ''dict''>, {''now'': {(''%Y-%m-%d'',): ''2021-10-15'', (''%H-%M-%S'',): ''22-50-14''}}),
    key_type=typing.Any, element_type=typing.Any)'
_parent:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.10
    start_time: 1634318410
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 15
      4: 3.8.10
      5: 0.12.4
      8:
      - 2
      - 5
